; Plant Autonomy Testbed — Phase 2 integrated firmware
; See DL-040 for architectural principles.

[env:wrover]
platform = espressif32
board = esp-wrover-kit
framework = arduino

monitor_speed = 115200
upload_speed = 460800

upload_port = /dev/cu.usbserial-1140
monitor_port = /dev/cu.usbserial-1140

build_flags =
    -DBOARD_HAS_PSRAM

lib_ldf_mode = deep

lib_deps =
    knolleary/PubSubClient@^2.8
    adafruit/Adafruit BME280 Library@^2.2.4
    claws/BH1750@^1.3.0
